GET https://cloud-function-gfcragd9c3fvgqcn.polandcentral-01.azurewebsites.net/api/hello/world

###
GET https://cloud-function-gfcragd9c3fvgqcn.polandcentral-01.azurewebsites.net/api/hello/world

###

GET http://localhost:7071/api/calculator/3/5
