GET https://cloud-function-gfcragd9c3fvgqcn.polandcentral-01.azurewebsites.net/api/hello/world

###
GET https://cloud-function-gfcragd9c3fvgqcn.polandcentral-01.azurewebsites.net/api/hello/world

###

GET http://localhost:7071/api/calculator/3/5

###

GET https://cloud-function-gfcragd9c3fvgqcn.polandcentral-01.azurewebsites.net/api/calculator/{a:int}/{b:int}

###

GET http://localhost:7071/api/calculator/3/5/add

###

GET http://localhost:7071/api/calculator/3/5/subtract

###

GET http://localhost:7071/api/calculator/3/5/multiply

###

GET http://localhost:7071/api/calculator/3/5/divide
